### ISSUE TITLE
Smoothed argmaxes: α-entmax

### ISSUE THREAD

**Issue by nunonmg** [deep-spin/tutorial#3]
Thank you for the tutorial!
In slide 80 of the ACL version, shouldn't the α-entmax formulation be: 1/α(α-1) sum_j (p_j - p_j^α) ?

**Comment by vene** [comment]
Hi Nuno, sorry for the huge delay on this: the notification email slipped through the cracks somewhere. Sorry!

The answer is yes and no, here is why:

1) Your expression is the Tsallis entropy H_α(p). The regularizer we use on slide 80 here is Ω = -H (note the minus sign.) So indeed if you were to plug in Ω = -H_α, ie the negative of the expression in your message, you would get the correct result.

2) Now since the domain of Ω is the simplex, we have that sum_j p_j = 1, so the negative of your expression can be written as

Ω(p) = 1/α(α-1) sum_j (p_j^α - p_j) = 1/α(α-1) [sum_j p_j^α - sum_j p_j] = 1/α(α-1) [(sum_j p_j^α) - 1]

and notice that the constant term at the end can be ignored as it does not affect the minimizer. 

Hope this clears things up!
